/**
 * maketape.mjs — generate `demo.tape` from `agent.ts`.
 *
 * The tape drives LazyVim to type the hero file live and run it. We enter Vim's
 * `:set paste` mode first so autopairs / autoindent don't mangle the brackets and
 * indentation as VHS sends literal keystrokes. Leading tabs are rendered as two
 * spaces for the typed copy (it runs identically).
 *
 *   node maketape.mjs   # writes demo.tape
 */
import { readFileSync, writeFileSync } from "node:fs"

const src = readFileSync(new URL("./agent.ts", import.meta.url), "utf8").replace(/\n$/, "")

// VHS has no string escaping, so wrap each Type in a delimiter the line does NOT
// contain (prefer backtick, then ", then '). agent.ts is written so no line needs
// all three. Tabs → 2 spaces for the typed copy (runs identically).
const typeLine = (raw) => {
	const line = raw.replace(/\t/g, "  ")
	const delim = !line.includes("`") ? "`" : !line.includes('"') ? '"' : "'"
	if (line.includes(delim)) throw new Error(`no safe delimiter for: ${line}`)
	return `Type ${delim}${line}${delim}\nEnter`
}

// Blank lines fall between logical blocks — turn each into a short beat pause so
// the typing breathes in step with the voice-over.
const lines = src.split("\n")
const body = lines
	.map((line) => (line === "" ? `Enter\nSleep 900ms` : typeLine(line)))
	.join("\n")

const tape = `# demo.tape — GENERATED by maketape.mjs; edit agent.ts, then regenerate.
# Record:  vhs demo.tape   → demo.mp4  (silent screen capture; VO is muxed by build.sh)
Output demo.mp4

Require nvim
Require node

Set Shell "zsh"
Set FontFamily "JetBrainsMono Nerd Font Mono"
Set FontSize 18
Set Width 1600
Set Height 1000
Set Padding 24
Set Theme "Catppuccin Mocha"
Set TypingSpeed 28ms

# open the buffer, clear anything left from a previous take, then paste-mode
# (paste mode defeats LazyVim autopairs/autoindent during literal typing)
Type "nvim demo.ts"
Enter
Sleep 1.2s
Escape
Type ":%d"
Enter
Type ":set paste"
Enter
Type "i"
Sleep 400ms

# ── type the hero, live ──
${body}

# save and run
Escape
Sleep 500ms
Type ":wq"
Enter
Sleep 800ms
Type "node demo.ts"
Enter
Sleep 9s
`

writeFileSync(new URL("./demo.tape", import.meta.url), tape)
console.log(`demo.tape written (${lines.length} source lines)`)
