#!/usr/bin/env bash
# Execute every extracted Clojure docs example — on BOTH hosts, in FOUR modes.
#
# The other six runners answer "does this example still compile and run". This one
# answers a second question the Clojure port exists to answer: does it do the same
# thing on the JVM and on cljgo? A documented example that works under `clojure -M`
# and fails under `cljgo build` is exactly the drift this port was written to
# prevent, and a single-mode runner could not see it.
#
#   deps-main   clojure -M   with deps.edn        JVM,   compiled-on-load
#   deps-repl   forms piped into clojure -r       JVM,   REPL evaluator
#   cljgo-run   cljgo run                         cljgo, interpreted
#   cljgo-aot   cljgo build -> native binary      cljgo, AOT-emitted
#
# Hermetic: a scratch project whose :paths point at THIS repo's clojure/src, so the
# examples run against local code and a renamed function fails the run. koine comes
# from Clojars, exactly as a consumer would get it — the same version deps.edn pins.
#
# Each snippet is a file of top-level forms ending in (println "OK"), with `assert`
# doing the real work. stdout is shown on failure; a snippet that throws fails.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SNIPPETS="$REPO_ROOT/site/tests/snippets/clojure"
WORK="$REPO_ROOT/site/tests/.work/clojure"

if [ ! -d "$SNIPPETS" ]; then
	echo "no clojure snippets — run: node site/scripts/extract-snippets.mjs"
	exit 0
fi

# The koine version is READ from the port's own deps.edn rather than repeated here.
# A second copy of a version number is a second thing to forget: the docs examples
# must run against the dependency the port actually ships with.
KOINE=$(grep -o 'net.clojars.muthuishere/koine {:mvn/version "[^"]*"' "$REPO_ROOT/clojure/deps.edn" \
	| grep -o '[0-9][^"]*')
if [ -z "$KOINE" ]; then
	echo "FAIL: could not read the koine version from clojure/deps.edn" >&2
	exit 1
fi

rm -rf "$WORK"
mkdir -p "$WORK/src"

cat > "$WORK/deps.edn" <<EOF
;; Generated by site/tests/runners/clojure.sh — the docs-example sandbox.
{:paths ["src"]
 :deps  {org.clojure/clojure               {:mvn/version "1.12.5"}
         net.clojars.muthuishere/koine     {:mvn/version "$KOINE"}}}
EOF

cat > "$WORK/build.cljgo" <<EOF
;; Generated by site/tests/runners/clojure.sh — the cljgo half of the same sandbox.
;; cljgo takes its sources from src/ by convention, which is why the port's own
;; tree is COPIED in below rather than added as a second source path: there is no
;; source-path verb, and inventing one fails the build with an unresolved symbol.
(defn build [b]
  (dep b "net.clojars.muthuishere/koine" {:mvn/version "$KOINE"})
  (install b (exe b {:name "snippet" :main "src/snippet.cljc"})))
EOF

# The port's source, copied in so BOTH toolchains see one tree: deps.edn resolves
# it through :paths and cljgo through its src/ convention. A copy rather than a
# symlink because cljgo walks the tree, and it is refreshed on every run, so a
# stale copy cannot pass while the real source is broken.
cp -R "$REPO_ROOT/clojure/src/toolnexus" "$WORK/src/toolnexus"

have_cljgo=1
command -v cljgo >/dev/null 2>&1 || have_cljgo=0
[ "$have_cljgo" -eq 1 ] || echo "  note: cljgo not on PATH — the two cljgo modes are REPORTED AS SKIPPED, not passed"

pass=0
fail=0
skipped_cljgo=0
failed_names=()

# A mode fails if the snippet throws OR if it never reached its final (println "OK").
# Exit status alone is not enough: the cljgo REPL prints errors on stderr and CONTINUES
# to the next form, so a snippet whose middle form blew up can still exit 0.
run_one() { # $1 = mode label, $2 = command, $3 = snippet name
	local mode=$1 cmd=$2 name=$3 out
	out=$(cd "$WORK" && eval "$cmd" 2>&1)
	if [ $? -ne 0 ] || ! printf '%s' "$out" | grep -q '^OK$'; then
		printf '  \033[31mFAIL\033[0m %-34s %s\n' "$name" "$mode"
		printf '%s\n' "$out" | sed 's/^/        /' | head -15
		return 1
	fi
	return 0
}

for f in "$SNIPPETS"/*.cljc; do
	[ -e "$f" ] || continue
	name="$(basename "$f" .cljc)"
	cp "$f" "$WORK/src/snippet.cljc"
	bad=0

	run_one "deps-main" "clojure -M -e \"(load-file \\\"src/snippet.cljc\\\")\"" "$name" || bad=1
	run_one "deps-repl" "printf '(load-file \"src/snippet.cljc\")\n' | clojure -r" "$name" || bad=1

	if [ "$have_cljgo" -eq 1 ]; then
		# BUILD FIRST, then run. `cljgo run` refuses to resolve a declared
		# dependency without a build.lock.edn (G5023), so the AOT leg is what
		# pins the lock the interpreted leg then reads.
		built=0
		(cd "$WORK" && cljgo build >/dev/null 2>&1) && [ -x "$WORK/snippet" ] && built=1
		run_one "cljgo-run" "cljgo run src/snippet.cljc" "$name" || bad=1
		if [ "$built" -eq 1 ]; then
			run_one "cljgo-aot" "./snippet" "$name" || bad=1
		else
			printf '  \033[31mFAIL\033[0m %-34s %s\n' "$name" "cljgo-aot (build failed)"
			(cd "$WORK" && cljgo build 2>&1 | sed 's/^/        /' | head -10)
			bad=1
		fi
	else
		skipped_cljgo=$((skipped_cljgo + 1))
	fi

	if [ "$bad" -eq 0 ]; then
		pass=$((pass + 1))
		if [ "$have_cljgo" -eq 1 ]; then
			printf '  \033[32mPASS\033[0m %-34s 4 modes (JVM main+repl, cljgo run+aot)\n' "$name"
		else
			printf '  \033[32mPASS\033[0m %-34s 2 modes (JVM main+repl; cljgo SKIPPED)\n' "$name"
		fi
	else
		fail=$((fail + 1))
		failed_names+=("$name")
	fi
	rm -f "$WORK/snippet"
done

echo ""
if [ "$skipped_cljgo" -gt 0 ]; then
	echo "Clojure: $pass passed, $fail failed — cljgo SKIPPED for $skipped_cljgo snippet(s), so this run proves the JVM half only"
else
	echo "Clojure: $pass passed, $fail failed (each on all four modes, both hosts)"
fi
[ "$fail" -eq 0 ] || { printf 'failed: %s\n' "${failed_names[*]}"; exit 1; }
